#server:
#  port: 8999
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/wedding?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 980328
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.wedding.model.po  #
#
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
